import { Testimonial } from "../types";

export const testimonials: Testimonial[] = [
  {
    testimonial:
      "The role you played in my life is not only because of being colleagues at work. To be honest, I’ve never met anyone who is more kind-hearted, caring, and supportive than you. I wish you a lot of success because you deserve it. Thank you for being such an elder bro rather than a colleague.",
    name: "Asima Chowdhury",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial: "Thank you for helping and doing a quick fix.",
    name: "Bushra Nawar",
    designation: "Backend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I know it's difficult to switch between projects, but you have managed it really well and delivered on all fronts. KUDOS",
    name: "Akhil Verlekar",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "You have always risen to challenges that have come your way. Completing Hexagone CAM email within 3 hrs is another amazing feet you have achieved. Hats off.",
    name: "Akhil Verlekar",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "It's great to have you in my team, your attention to detail has been apricated by the client on Zimbroom project. It's just the start of the project but I feel confident for a successful project with your leadership qualities.",
    name: "Akhil Verlekar",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thankyou Rajon for always helping me out right from the day I joined SJI. You are really good mentor and always there to guide whenever any difficulty arises. Your quick responses to my queries and KT's were always helpful. Thankyou once again.",
    name: "Yuvraj Arondekar",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Congratulations on your service's 3rd anniversary today! You have been such a significant part of our team and we couldn't imagine your workplace without you.",
    name: "kibria chowdhury",
    designation: "HR",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for your proactive actions to solve the Lauren Jansen issue, considering the mail going live in few hours time it was critical we solve the issue. Amazing job",
    name: "Akhil Verlekar",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Good to your approach, you are the only one from our team I guess who had added personal objective. Great keep it up Q1-2022: Learning: Redux for React, NodeJs Basic for relating with backend. Project: 2 React Projects, 1 Highly interactive webpage with scroll animations.",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Innovation",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your effort made us feel a little more special. Thank you for arranging a nice event on the eve of women's day.",
    name: "Bushra Nawar",
    designation: "Backend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I can’t believe how lucky I am to have a great colleague like you. I appreciate the efforts made during the arrangement. l am happy to accept your all gifts. On behalf of all women thank you...!!",
    name: "Asima Chowdhury",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thanks for your contribution and support in the annual picnic. Without your support, it was hard to maintain all things. Thanks a lot.",
    name: "Debangshu Das",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for bringing your positive attitude in working environment. Your help has made my job much easier and more enjoyable. I really appreciate your time and effort. Have a joyful Thanksgiving!",
    name: "kibria chowdhury",
    designation: "HR",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "You have been a great support to the team. Your help and suggestions are always effective for me. Thanks for being an amazing teammate. Happy Thanks Giving :)",
    name: "Monira Heya",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for all your hard work to complete Javascript goals it is really a great achievement for us and now we can plan and target to achieve the next goals. It was amazing to see the implementation of your silks for the final mini-projects. Please keep up the good work :)",
    name: "Ketan Kamat",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "It is my Pleasure to announce that you have been shortlisted as Performer of the month for the month of September 2021. On behalf of the entire SJI team I congratulate and Thank you for showing such a great commitment and dedication towards your work and responsibility.",
    name: "Madhav Ranganekar",
    designation: "COO",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Every single day, you inspire us with your good work... Keep it up",
    name: "Jilal Ahmed",
    designation: "HR Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Finally, we have completed our long-awaited JavaScript goal and it's a big achievement for all of us. Thank you for the dedication you have shown for the past two Quarters and with the same energy and enthusiasm let's get set to achieve our next goal and upgrade our technical skills to the next level. Thank you Team!",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for going above and beyond to help us deliver the task to Jared. We wouldn’t have made it without you. Thank you for setting such a fantastic example!",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for going above and beyond to help StormBrain client during the on-call schedule last week. Your extraordinary attention to detail took this project to another level.",
    name: "Sayeed Ahmed",
    designation: "Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial: "Your work flexibility is the key asset for the company.",
    name: "Sayeed Ahmed",
    designation: "Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your Hubstaff hrs & activity has improved significantly for the past 2 weeks to meet our organization standard. Please keep it up.",
    name: "Sayeed Ahmed",
    designation: "Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "It was amazing to see your progress and hard work to complete the last quarter's goals. also thanks for sharing the nice points during your book presentation. :) please keep up the good work.",
    name: "Ketan Kamat",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Innovation",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I would like to thank you for helping us with Tracy's new request for Shopify and Klaviyo email templates. You had done a good job of doing r&d for this task as we had worked on it for the first time. It was really great to see you putting all your efforts also communicating with the client to deliver this task perfectly. Keep up the good work.",
    name: "Ketan Kamat",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I feel so proud to be a part of this wonderful team, congratulations to everyone for the hard work and dedication you have shown towards completing your goals. Thank you Team.",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "It's great to see how you have raised the bar of your work abilities and taken responsibility for client projects like ferring. For your excellent performance and contribution we have shortlisted you as one of the Performer of the month for April 2021. Congratulations !",
    name: "Madhav Ranganekar",
    designation: "COO",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "You have really amazed many as a real example of humbleness. You never say no and jumped into rescue whenever required. And special thanks for shutting my pc off after that long update at night.",
    name: "Mahmudul Hassan",
    designation: "Team Lead",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "It was great to complete EOS book reading Goal and it was not possible without your extra efforts. I would also like to thank you for sharing the valuable points during the book reading presentation.",
    name: "Ketan Kamat",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I am very Happy with the progress on Goals. Keep it up guys. Let's do this. The harder you work for something, the greater you’ll feel when you achieve it.",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I'm impressed by your commitment and the way you took the effort to make the videos. Long way to go! looking forward to it.",
    name: "Sanjeet Kanekar",
    designation: "Graphics Designer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Innovation",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for putting in extra effort to get the EOS book reading goal completed on time. The takeaways from this book were valuable points.",
    name: "Akhil Verlekar",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I really appreciate how you are mentoring Debangshu. when I heard good news from others its always make me proud so I hope your effort will be same in future , Please keep it up your good work.",
    name: "Jilal Ahmed",
    designation: "HR Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial: "For such nice work on an emergency project on Task 1471",
    name: "MASUD AHAMMAD",
    designation: "Project Coordinator",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial: "Thanks for the informative session on Tailwind.",
    name: "Shreya Sangaonkar",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I truly feel privileged to be able to sent some good wishes to you where pandemic has stroke with its full power and we survived. May the new year brings you and your family good health and a lot of happiness.",
    name: "Mahmudul Hassan",
    designation: "Team Lead",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2021",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you so much for working like your life was at bet! I couldn’t have asked for better teammates! Thank you for having trust and faith in me as your Team Leader. We have won 2020 and so we will in 2021. Welcome 2021, Let's make it a great year.",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your Tech session on Tailwind was really informative and helpful. I really appreciate your effort and willingness to share knowledge with team members. You were the first person to voluntarily came forward to start the session. Thank you. Keep it up.",
    name: "Monira Heya",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "So glad you came up with your own interest and took the session on TailWind with Sylhet office. You have explained well. Really happy to see you pushing yourself outside the box. Keep it up.",
    name: "Mahmudul Hassan",
    designation: "Team Lead",
    company: "SJ Innovation LLC",
    image: "",
    category: "Innovation",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Today I got an opportunity to thank you. It is really nice to work with you. You make the workplace like home for me, where I can work, spend a good environment. Thanks for all the help in the past days. Wish you a happy and beautiful thanksgiving day.",
    name: "Tasmia Sunna",
    designation: "QA Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I want to express my appreciation for you. Working with you has been an amazing opportunity. I appreciate your high standards, your persistence, your encouragement, and your sense of humor. Thank you for making this team a great success. I wish you a joyful Thanksgiving.",
    name: "Makdia Hussain",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I want to take time to thank you for what you do to make SJI a place to work in. We wouldn't be here without your contribution. A very happy thanks giving to you.",
    name: "Partha Sarathi Kundu",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for making SJ Innovation an enjoyable place to work, and for being an excellent teammate. I appreciate all that you do for me and the team. Happy Thanksgiving.",
    name: "Monira Heya",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I am so deeply thankful for being surrounded by some amazing people like you throughout the year. Happy Thanksgiving to you all!",
    name: "Bahlul Siddiquee",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I want to let you know just how much I appreciate your hard work and dedication to our team. You've done an incredible job, and your support has been a huge part of our success. I'm so thankful to have you as a teammate and look forward to working with you in the new year. Happy Thanksgiving!",
    name: "Fokrul Hasan",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "You have done a good job working on the certificate tasks on the Janssen project and we were able to deliver the task quickly as per the client's request. Also thanks for helping us with bill cole frontend work and also delivering the priority Ferring tasks. You are really hardworking and I appreciate your work. Please keep up the good work.",
    name: "Ketan Kamat",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for the countless times you have come to my aid in times of need. For all the KT on Janssen and JMC and the patience, you have with me",
    name: "Caesar D’Silva",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your presence matters a lot to the team and the company. Thank you for all your efforts and dedication in building a strong ethic. Keep it up.",
    name: "Mahmudul Hassan",
    designation: "Tech Lead",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you front end boss , for helping me yesterday on the CSS player related fixes , i am very thankful to you for this. Also thank you for everytime helping me on the JMC related CSS issues :)",
    name: "Bahlul Siddiquee",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thanks for making the Sylhet team awesome by working together. Thank you for all the help and support provided by you. Happy and beautiful Thanksgiving day 2u.",
    name: "Jilal Ahmed",
    designation: "HR Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Keep up the good work you are doing Rajon. Your communication has improved a lot, I see you taking lot of small initiatives. Get ready for some more amazing task in the upcoming months. Thank you",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for all the help Rajon, you are truly invaluable, the effort and the dedication and the countless times you have worked over your shift hours to make the client successful is appreciated. To be working with you is a pleasure",
    name: "Caesar D’Silva",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "in SJI i have met so many developers, all of them are really good. but i would like to mention your one quality, that impressed me a lot, the way you put comment in every task with details, this this is really amazing nd others should learn it from you i believe. good luck",
    name: "Laila Chaity",
    designation: "Graphics Designer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "A big thank you for all that you have done. I appreciate your efforts and hard work you put in on the Janssen project. I wish that you continue your spirit in the upcoming days.",
    name: "Pritesh Parshekar",
    designation: "Technical manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you for your continuous support and help . I appreciate everything that I’ve learned from you. Thank You!",
    name: "Naimun Jeba",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your efforts, hard work and flexibility clearly shows how you are maturing as team member taking additional responsibilities and showing Urgency on this important project of janseen. Great part is you are also contributing in other projects as well and not restricting yourself. Thank you for your contribution. I am pleased to inform , you have been selected as Performer of the month for September 2020. Thank you.",
    name: "Madhav Ranganekar",
    designation: "COO",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Whenever I call for any help either it is development related or just to share ideas I find you there always. You are real awesome and example of SJ culture to live by. Thanks a ton for that.",
    name: "Partha Sarathi Kundu",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "HR raised a concern during the stakeholders and many other meetings that team members hardly respond to the emails. An email, even from the company CEO got only 7 replies yesterday where we stand 19 in the Sylhet office even after giving both verbal and written reminders. Try taking out 10-15 mins of your time and reply to your emails wherever needed.",
    name: "Mahmudul Hassan",
    designation: "Team Lead",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your quick response to the UI fix in EMR really saved a lot of time. That's an ideal example of teamwork and being humble. Really appreciate.",
    name: "Mahmudul Hassan",
    designation: "Team Lead",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "It was really amazing to achieve the desired output for the email and Certificate task as per the client's request. We know it was the first time which we had worked on this kind of task and we had to do lots of R&D and try some things out from our end but you had done it well. I would like to Thank you for putting extra efforts into this task.",
    name: "Ketan Kamat",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      '"Success is peace of mind which is a direct result of self-satisfaction in knowing you did your best to become the best you are capable of becoming" Thank you for doing all the hard work for Janssen Newsletter and making client happy.',
    name: "Sayeed Ahmed",
    designation: "Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "As you are a interviewer you did excellent job today . I feel so proud as i am a your team member .",
    name: "Jilal Ahmed",
    designation: "HR Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your commitment and dedication to making the client successful has been a saving grace",
    name: "Caesar D’Silva",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your flexibility and willingness has helped us deliver a lot of tasks and have helped us improve our reputation",
    name: "Caesar D’Silva",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "The way you're doing your work every day is tremendous. You might be doing your regular work but way you're handling Janssen we all appreciate it. Every time I went to you, you never let me go empty-handed. Though you had 5/6 tasks in your hand you managed to take mine and let me work on other priority projects. From last 2/3 month, only 2 devs are taking care of Janssen but in night shift the support you're giving to PM, QA and the team is noticeable. Keep up the good work, learn, explore and most importantly keep moving forward. Proud to have you in the team :)",
    name: "Nazifa Rashid",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I would like to thank you for putting extra efforts and being available whenever we needed you and it would have not been possible to deliver the high priory task marked by the client within the given timeline. Thank you so much for your hard work and please keep up the good work.",
    name: "Ketan Kamat",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I just wanted to thank you all. I couldn't see myself here after this 2 years without all your support and help. I am really fortunate to have you all as my teammate and learn from you all day in day out.",
    name: "Partha Sarathi Kundu",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your efforts on the sjtelehealth helped in delivering the website on time and with good quality. Keep it up.",
    name: "Akhil Verlekar",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Congratulations for getting Performer of the month award for month of Jan 2020. The way you have handled your work , taking half baked tasks and fixing them to ensure timely delivery and also ensured your team commitment is followed. Thank you for your contribution and keep us the good work.",
    name: "Madhav Ranganekar",
    designation: "COO",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "you are awesome! I feel fortunate to have you all in my team nd learn so many things form you all. Late shift team rocks!",
    name: "Partha Sarathi Kundu",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Please concentrate your late coming. You are late multiple days in the month of January.",
    name: "Jilal Ahmed",
    designation: "HR Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2020",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "The way you work makes me realize that sooner you will be able to reach heights of success. ...",
    name: "Jilal Ahmed",
    designation: "HR Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Excellent session today, I am impressed. Keep it up and continue doing it always. Thanks",
    name: "Pritesh Parshekar",
    designation: "Technical Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "During month of September your DHS posting was 100% . Thank you for this consistency towards this important basic process. Its motivating for all of us.",
    name: "Madhav Ranganekar",
    designation: "COO",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Good job. I see you delivered the urgent task on time. It's actually nice to hear about teammates from others. I can see all your hard work on Janssen. Keep it up and improvise get better at what you do",
    name: "Munni Modak",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "You are doing good but a extra little effort can make you a better version of yourself in your daily work. Hope you will learn from the mistakes on JMC and keep them in mind going forward.",
    name: "Partha Sarathi Kundu",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "mistakes happen but not being open about mistakes will hurt the team more. please be careful in future and always be OPEN on issues. We are a team and will get solutions together.",
    name: "Omprasad Desai",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Before leaving you must have to check your food plates,coffee mug,spoon and other are well clean along door lock and electrical whole switch are off. Please don’t forget.",
    name: "Jilal Ahmed",
    designation: "Project Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "you are running like Rocket! Nice to see your progress overall. Look forward you to take much more responsibility as well towards making a better team. Share your expertise as much as you can with your team mates. It is the only way to make you updated as well as compatible with new technologies.",
    name: "Partha Sarathi Kundu",
    designation: "Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "You're a fast learner and very good at frontend work. Tasks you're doing on both Janssen & JMC are up to the mark for a beginner. Also you're putting great effort in your learning project. The way you completed theme development was impressive. Also you implemented that on your portfolio was very good . Keep up the good work and thanks for your effort towards Janssen & JMC. And thanks for EOD update!",
    name: "Nazifa Rashid",
    designation: "UI/UX Designer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your DHS posting was not consistent and low in Month of June. Please be aware that this is one of the important and Basic Company process which we expect every one to respect and follow.",
    name: "Madhav Ranganekar",
    designation: "COO",
    company: "SJ Innovation LLC",
    image: "",
    category: "Company Culture",
    year: "2019",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Rajon's exceptional performance on our two most crucial web development projects deserves high praise. By skillfully leveraging the Lovable AI mockup reference and implementing it within the WordPress environment on GHL, Rajon has demonstrated outstanding technical prowess and efficiency. Delivering high-quality results well within the given timeline, Rajon's work not only met but exceeded our expectations. This level of dedication and progress clearly aligns with our company's vision of harnessing AI tools to optimize project delivery. Rajon's adaptability, forward-thinking approach, and ability to push boundaries set a new benchmark for excellence. We're thrilled with Rajon's contributions, which are driving our success and paving the way for innovative solutions. Keep up the fantastic work, Rajon – your commitment to excellence is truly commendable, and we're excited to see your continued impact on future projects.",
    name: "Pranav Ashok Rivankar",
    designation: "Jr. Software Project Coordinator L2",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2025",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      'I wanted to touch base regarding the courses "Fundamentals of AI, ML, DL and GenAI" and "AI Academy Courses by IBM" that were assigned to you. These courses and the accompanying quizzes haven\'t been completed by you. These courses were crucial for our Q2 Company OKR: "Develop a leadership team of 5 members with expertise in AI solutions, ready to deliver tailored strategies to clients."',
    name: "Mohan Pai",
    designation: "Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Innovation",
    year: "2025",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Though this praise is a bit delayed, I want to express my gratitude for your extra effort in hiring Interns and Junior Front End Developers. Your support has been incredibly helpful. I hope you continue to excel and contribute even more in the future. I am truly thankful for your efforts.",
    name: "Mohammad Foysal",
    designation: "Sr. HR & Admin Executive L1",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Ketan Kamat, Denzil Diniz and Sashant Vishwakarma along with you. Above & Beyond We had high workload from Propelhealth today and some were very urgent. You guys realised client's urgency and you have put additional effort to ensure the delivery. Thank you for showing urgency and your additional effort !",
    name: "Akramol Hoque",
    designation: "Sr. Client Relationship Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "You are really good at mentoring. Your skill in DXP helped me a lot to learn and provide the task in time. Thanks a lot!",
    name: "Md Jasim Uddin",
    designation: "Jr. Software QA Engineer L3",
    company: "SJ Innovation LLC",
    image: "",
    category: "Mentorship",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thanks for leading the DXP project. You really helped everyone understand it better, and your KT given to team members have been great! Keep up the awesome work!",
    name: "Pritesh Parshekar",
    designation: "Assistant Manager (Technical)",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I wanted to take a moment to recognize the incredible teamwork you're demonstrating on the ongoing DXP and Albino's project. Juggling multiple projects and meeting deadlines can be a challenge, but you're all rising to the occasion. Thanks for keeping the team on track with this multi-project challenge. Let's keep this momentum going! We have a great team in place, and I'm confident we'll deliver a successful outcome on all projects. Thank you for all your efforts.",
    name: "Pritesh Parshekar",
    designation: "Assistant Manager (Technical)",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your contribution on PropelHealth & DXP project is greatly appreciated & also you exemplify the phrase Lead by example.",
    name: "Sevren Vaz",
    designation: "Assistant Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your dedication, additional efforts, and adaptability consistently inspire team members, enabling them to meet client project deadlines. Thank you for setting a leading example.",
    name: "Sayeed Ahmed",
    designation: "Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Leadership",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Partho Rahman and Reshad Sadik Mahi along with you. Above & Beyond The new website revealed.com went live on time before the event client had on Rare Disease Day. They are happy with the quality of work, timely delivery and appreciated us for our effort to build the entire site in such a short time. This would not be possible without the dedication you had and extra effort you guys gave as a team. You guys proved it again that if we work together, we can make 'impossible' things possible ! Thank you for going above and beyond to make the client successful.",
    name: "Akramol Hoque",
    designation: "Sr. Client Relationship Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2024",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Your dedication and hard work have been instrumental in achieving outstanding client success. Your commitment to excellence is truly commendable, and the team is fortunate to have such a dedicated member. Well done!",
    name: "Nium Chowdhury",
    designation: "Sr. Software Project Coordinator L1",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2023",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I wanted to express my heartfelt gratitude for your unwavering support. Your assistance during our recent project, and on multiple other occasions, has been a true lifeline. Your problem-solving skills and willingness to help have made all the difference. I genuinely feel fortunate to have you as my teammate. Your contributions have been pivotal, and I can't thank you enough for your generosity and expertise.",
    name: "Sushmita Das",
    designation: "Frontend Developer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Team Collaboration",
    year: "2023",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Great job with UNA Health! It was one of the smoothest projects I have handled, and it's all thanks to your efforts and the high quality you delivered. Keep it up and looking forward to working with you on another project.",
    name: "Akhil Verlekar",
    designation: "Program Manager L1",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2023",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "Thank you, Rajon for being a last moment life savior and helping me to fix css issues no matter what the platform is. I am glad to find you on our team.",
    name: "Bushra Nawar",
    designation: "Jr. Software Engineer",
    company: "SJ Innovation LLC",
    image: "",
    category: "Technical Excellence",
    year: "2023",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "The first & only person to contribute to Client success story form a senior member. Thank you for leading by example.",
    name: "Sevren Vaz",
    designation: "Assistant Manager",
    company: "SJ Innovation LLC",
    image: "",
    category: "Client Satisfaction",
    year: "2022",
    rating: 5,
    featured: false,
  },
  {
    testimonial:
      "I would like to thank you Rajon for helping us with the urgent request from Gary Bunofsky | Acquisition Email template project. I appreciate your efforts in completing the email template by joining from home. This is the reason the client is happy and confident with our work.",
    name: "Ketan Kamat",
    designation: "Sr. Software Project Coordinator L1",
    company: "SJ Innovation LLC",
    image: "",
    category: "Project Delivery",
    year: "2022",
    rating: 5,
    featured: false,
  },
];
